site_name: ULHPC Documentation
nav:
- Home: 'index.md'
# - Organization: 'layout.md'
# - Pre-Requisites and Repository Setup: 'setup.md'
# - Contributing:
#   - Overview: 'contributing/index.md'
#   - Directory Layout: 'layout.md'
#   - Repository Setup and Git Developments: 'contributing/setup.md'
#   - Semantic Versioning: 'contributing/versioning.md'

# Project Information
site_name: ULHPC Documentation
site_description: ULHPC Technical Documentation
site_author: ULHPC Team
site_dir: public
site_url: "https://docs.hpc.uni.lu/"

# Repository
repo_name: www/ulhpc-docs
repo_url: https://gitlab.uni.lu/www/ulhpc-docs
#edit_uri: blob/master/docs/

# Copyright
copyright: Copyright &copy; 2007 - 2020 UL HPC Team

# Configuration
# strict: true

theme:
  name: material
  logo: images/logo_ULHPC_square.jpg
  language: en
  palette:
    primary: blue
    accent: light blue

plugins:
  - search # necessary for search to work
  - git-revision-date-localized:
      type: date

# Extras
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ULHPC
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.uni.lu/ULHPC
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ULHPC

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.details
  - toc:
      permalink: true
