site_name: ULHPC Technical Documentation
nav:
  - General:
    - Home: 'index.md'
    - Getting Started: 'getting-started.md'
    - Accounts:
        - Get an Account: 'accounts/index.md'
        - Password Policy: 'accounts/passwords.md'
        - Collaboration Accounts: 'accounts/collaboration_accounts.md'
        - Identity Management Portal: 'accounts/ipa.md'
        - Slurm Account Hierarchy: 'accounts/hierarchy.md'
  - Data Center:
    - Centre de Calcul (CDC): 'data-center/index.md'
  - ULHPC Supercomputers:
    - Overview: 'systems/index.md'
    - Iris:
        - Iris System: 'systems/iris/index.md'
        - Compute Nodes: 'systems/iris/compute.md'
    # - Aion:
    #     - Aion Supercomputer Overview: 'systems/aion/index.md'
  - Web Portals:
    - ULHPC Website: https://hpc.uni.lu
    - Technical Documentation: https://hpc-docs.uni.lu
    - IPA Portal: https://***REMOVED***
    - OpenOn Demand: https://hpc.uni.lu
    - ULHPC Tutorials: https://ulhpc-tutorials.readthedocs.io/

# tab Clusters:
# - Organization: 'layout.md'
# - Pre-Requisites and Repository Setup: 'setup.md'
# - Contributing:
#   - Overview: 'contributing/index.md'
#   - Directory Layout: 'layout.md'
#   - Repository Setup and Git Developments: 'contributing/setup.md'
#   - Semantic Versioning: 'contributing/versioning.md'

# Project Information
site_name: ULHPC Technical Documentation
site_description: ULHPC Technical Documentation
site_author: ULHPC Team
site_dir: public
site_url: "https://docs.hpc.uni.lu/"

# Repository
repo_name: www/ulhpc-docs
repo_url: https://gitlab.uni.lu/www/ulhpc-docs
#edit_uri: blob/master/docs/

# Copyright
copyright: Copyright &copy; 2007 - __YEAR__ UL HPC Team

# Configuration
# strict: true

theme:
  name: material
  logo: images/logo_ULHPC_square.jpg
  language: en
  palette:
    primary: blue
    accent:  light blue
  # features:
  #   - tabs

plugins:
  - search # necessary for search to work
  - git-revision-date-localized:
      type: date
  - progress

# Extras
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ULHPC
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.uni.lu/ULHPC
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ULHPC

# Extra stylesheets (incl. Twitter Bootstrap)
extra_css:
  - stylesheets/extra.css
  # - stylesheets/bootstrap.min.css
# Extra javascript
extra_javascript:
  - javascripts/extra.js
  - javascripts/bootstrap.min.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js

# Extensions
markdown_extensions:
  - attr_list
  # notes, warnings, hints, ...
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - markdown.extensions.admonition
  - pymdownx.arithmatex
  - pymdownx.details
  # Icons from Emoji extensions, giving access to following icon sets:
  # - Material Design: https://materialdesignicons.com/
  # - FontAwesome:     https://fontawesome.com/icons?d=gallery&m=free
  # – Octicons:        https://octicons.github.com/
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # auto-link HTML, FTP, and email links
  - pymdownx.magiclink:
      repo_url_shorthand: true
      social_url_shorthand: true
  - pymdownx.smartsymbols
  # code blocks with syntax highlighting, graphs
  - pymdownx.superfences
  - toc:
      permalink: true
