# -*- mode: yaml; -*-
# Time-stamp: <Wed 2022-06-01 00:07 svarrette>
################################################################################
# documentation: https://help.github.com/en/articles/workflow-syntax-for-github-actions
#
name: deploy-prod
on:
  push:
    branches:
      - production
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: install mkdocs
        run: |
          pip install mkdocs mkdocs-material mkdocs-material-extensions mkdocs-git-revision-date-localized-plugin mkdocs-include-markdown-plugin mkdocs-minify-plugin mkdocs-plugin-progress pymdown-extensions
          mkdocs --version
      - name: build ULHPC documentation
        run: mkdocs build --strict && mkdocs gh-deploy --force
